### PR TITLE
Update specification links

### PR DESCRIPTION
**Pull request by Progdrasil**
Update specification links to latest working draft.

### CODE REVIEW

**Comment by Progdrasil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Progdrasil** [comment]
recheck

**Comment by dturnerx** [comment]
The new specs will be posted on Friday, Oct 18.

**Comment by Vogeltak** [comment]
This is good to merge as is OR we can update it to the dedicated [Credential Exchange specification](https://fidoalliance.org/specifications-credential-exchange-specifications/) page on the FIDO Alliance's website.

**Pull request merged**
